# Generated by Django 4.2.5 on 2023-09-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_contraseña_usuario_contrasenia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasenia',
            new_name='contraseña',
        ),
    ]
