# Generated by Django 4.2.5 on 2023-09-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_contrasenia_usuario_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
